name: Build .deb package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ucode/

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install devscripts build-essential lintian libjson-c-dev debhelper-compat debhelper

      - name: Build package
        run: |
          cd ucode/
          export DEBFULLNAME=CI
          export DEBEMAIL=autobuild@invalid
          export GITVERSION=$(git describe --long --tags)
          export DEBVERSION=${GITVERSION#v}
          dch -v "${DEBVERSION%-*}" "Autobuild of $GITVERSION"
          dpkg-buildpackage -b -us -uc

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: deb
          path: '*ucode*.deb'
